### ISSUE TITLE
Bundling error while using Webpack 5, implicit JSON imports

### ISSUE THREAD

**Issue by zychu312** [lumada-design/hv-uikit-react#2684]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

I am working on a project which is using your components. 

We are using Webpack 5 and compilation returns bunch of errors e.g.

```
ERROR in ../../.yarn/__virtual__/@hitachivantara-uikit-react-core-virtual-ecb58e0d52/0/cache/@hitachivantara-uikit-react-core-npm-3.56.2-bcfadfc48c-12fe702f06.zip/node_modules/@hitachivantara/uikit-react-core/dist/modern/theme/index.js 8:0-70

Module not found: Error: Can't resolve '@hitachivantara/uikit-common-themes/dist/dawn' in '/home/dawid.m.zych/Projects/frontend/.yarn/__virtual__/@hitachivantara-uikit-react-core-virtual-ecb58e0d52/0/cache/@hitachivantara-uikit-react-core-npm-3.56.2-bcfadfc48c-12fe702f06.zip/node_modules/@hitachivantara/uikit-react-core/dist/modern/theme'
```

Which are caused by importing JSON files from @hitachivantara/uikit-common-themes/dist/ e.g.

`@hitachivantara/uikit-common-themes/dist/dawn`

without .json extension, while Webpack 5 expects

`@hitachivantara/uikit-common-themes/dist/dawn.json`

I am attaching GIT Diff which is fixing issues connected with importing JSON files without extension:

[@hitachivantara-uikit-react-core-npm-3.56.2-bcfadfc48c.txt](https://github.com/lumada-design/hv-uikit-react/files/8134156/%40hitachivantara-uikit-react-core-npm-3.56.2-bcfadfc48c.txt)

### Expected behavior 🤔

uikit-react-core can be used with Webpack 5 without workarounds

**Comment by francisco-guilherme** [comment]
Hi @zychu312. Thanks for reaching out. 

Can you provide more details on your app setup.
We've been using Webpack 5 on many applications consuming the UI-kit without any issues.
Mostly because we've been leveraging [CRA](https://create-react-app.dev/) that has all the configurations needed.
Please check if you're missing any needed configurations.

If you want take a look at these sample projects with the UI-Kit setup:
- js - https://codesandbox.io/s/hv-ui-kit-bug-report-jkm4f
