### ISSUE TITLE
[TagsInput] Input tags with , and space

### ISSUE THREAD

**Issue by shikhap2021** [lumada-design/hv-uikit-react#2685]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

Hi,
Currently  HvTagsInput works on only "enter" button , but our requirement is,  input should works on  ( " , " and  "space") button.
![Uploading Screenshot 2022-02-25 at 11.42.52 AM.png…]()

### Expected behavior 🤔

HvTagsInput should  works on  ( " , " and  "space") button as well like its work on enter

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by diogofscmariano** [comment]
hi @shikhap2021. Thanks for reaching out. Our component is following the Design System interaction guidelines. If your use-case exercises another approach I strongly suggest reaching out to them and bubbling up our feature request. Although, at the same time, I agree that our component in the uikit should be flexible to allow this use-case. I added this feat request in our backlog, but It might take awhile to get there because everyone is fully booked until the end of next week. Dont you want to take this opportunity to submit a pull request with this feature?

**Comment by shikhap2021** [comment]
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
