### ISSUE TITLE
Problem working with NextJS - SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by guilherme-jsv-soares** [lumada-design/hv-uikit-react#2752]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When setting up the HvProvider it crash on running
![image](https://user-images.githubusercontent.com/35031275/164496350-baffd63e-c95f-4fd1-8a35-d73241b84367.png)

### Expected behavior 🤔

It should open the NextJS default screen on the browser.

### Steps to reproduce 🕹

Steps:

1. `npx create-next-app@latest nextjs-test-app --typescript --use-npm`
2. change the react version to 17.0.2 because ui-kit doesn't support 18 yet
3. install ui-kit `npm install @hitachivantara/uikit-react-core @material-ui/core@^4.11.0 plotly.js-basic-dist@^1.55.2` 
4. import `HvProvider` on `_app.tsx`
5. start dev server: `npm run dev`
6. the terminal throws the error on the image above and the browser shows the same error on a nextjs error window.

Codesandbox link: https://codesandbox.io/s/nextjs-ui-kit-test-ktysxh

### Your Environment 🌎

Latest MacOS, Chrome, UI-Kit

**Comment by francisco-guilherme** [comment]
Hi @guilherme-jsv-soares, thanks for reaching out.

We created a [prerelease](https://github.com/lumada-design/hv-uikit-react/tree/next) branch where we'll be working on features for the next major (4.x). 
We plan to have it integrated with our CI/ CD process and publish it on npm in order to have those features available.

We published an initial version of our packages to unblock the NextJs integration.
You just need to use - @hitachivantara/uikit-<package>@next

I created a [repo](https://github.com/francisco-guilherme/hv-uikit-next-js) and a [sandbox](https://codesandbox.io/s/hv-uikit-next-js-q6gs38), that showcases a basic integration of Next.js with the UI Kit.
Please test it on your side and evaluate it.

Probably there are still issues with some components that might have references to web api stuff, but those can eventually be addressed separately.

**Comment by urkopineda** [comment]
Hi @francisco-guilherme ,

I'm working with @guilherme-jsv-soares and seems that even `next` version has the same `Unexpected token 'export'` problem.

I've created a [sandbox](https://stackblitz.com/edit/nextjs-xlqht7?file=pages/index.js) for you to test it out, but, **tl;dr**: When importing UI Kit directly in any `pages/*` file, fails. When importing UI Kit throw another component with `next/dynamic`, works. Please check `pages/_app.js` and `pages/index.js` for working and not working sections.

Regards,

Urko

**Comment by francisco-guilherme** [comment]
Hi @urkopineda , i shared before the [sandbox](https://codesandbox.io/s/hv-uikit-next-js-q6gs38) working.
You are missing the [next.config](https://codesandbox.io/s/hv-uikit-next-js-q6gs38?file=/next.config.js) file needed.
Please take a look again.

Tks

**Comment by urkopineda** [comment]
Hi @francisco-guilherme, true, it's working! Thanks!
