### ISSUE TITLE
Outdated dependency 'react-table' causes dependency conflicts

### ISSUE THREAD

**Issue by andyjansson** [lumada-design/hv-uikit-react#2806]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When installing `@hitachivantara/uikit-react-core` while also having `react@^17.x` installed, `npm install` produces `Conflicting peer dependency` warnings due to `react-table@6.8.6` not supporting `react@^17.x`. React 17.x should be supported according to [ui-react-core's peer dependencies](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/package.json#L46).

### Expected behavior 🤔

No warnings!

### Steps to reproduce 🕹

Steps:

1. `npm i react@17.0.2`
2. `npm i react-dom@17.0.2`
3. `npm i @hitachivantara/uikit-react-core`
4. `npm i`
5. BOOM!

### Context 🔦

This is causing a dependency mismatch.

### Your Environment 🌎

Device: Laptop
OS: Windows
Browser: N/A
Version: N/A

**Comment by francisco-guilherme** [comment]
Hi @andyjansson , tks for reaching out.

The error is due to the strict peerDependencies that is set in the npm version 7, and as of npm v7, peerDependencies are installed by default which results in conflict and causes the issue.

You can resolve the  dependency tree by using the --force flag while installing the dependencies, or you can ignore the peerDependencies by passing an additional argument --legacy-peer-deps.
