### ISSUE TITLE
Ability to specify component on HvDropdown

### ISSUE THREAD

**Issue by AJDowdsHV** [lumada-design/hv-uikit-react#2851]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

In the same way as we have the ability to specify a component for `HvBaseDropdown`, it would be nice if we could do the same on the `HVDropdown`. To be more specific, I am talking about the component which is clicked to trigger the dropdown menu to appear. In the screenshot below, it would be the button with the grid icon on it.

### Examples 🌈

![image](https://user-images.githubusercontent.com/105852608/180196626-2e80fc75-f8fd-4dc5-b5fe-b17446a520f4.png)

### Motivation 🔦

Trying to accomplish the above. It can be done using the `HVBaseDropdown` but `HvDropdown` already matches all of our other requirements. It just needs the ability to set the `component`.

**Comment by francisco-guilherme** [comment]
Hi @AJDowdsHV, that is not supported since is not aligned with Design System guidelines.
It makes sense and could be eventually an enhancement on our side.

We'll move this to our Backlog in order to be refined and prioritised.
Just to align the expectations, we will not tackle this very soon, since we working on a new Major version.

Tks
