### ISSUE TITLE
After Upgrading hitachivantara/uikit-react-core to 4.0.3 (Latest version)

### ISSUE THREAD

**Issue by chandinigangupalli** [lumada-design/hv-uikit-react#2944]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

After Upgrading to hitachivantara/uikit-react-core latest version the HvTable component is breaking .We are getting below mentioned error 

Error:
Uncaught TypeError: Cannot read properties of undefined (reading 'typography')
 The above error occurred in the <WithStyles(ForwardRef(HvTable))> component:

### Expected behavior 🤔

Before Upgrade to latest version HvTable components are working.

But After Upgraded to latest version HvTable is not working 

Uncaught TypeError: Cannot read properties of undefined (reading 'typography')
 The above error occurred in the <WithStyles(ForwardRef(HvTable))> component:

### Steps to reproduce 🕹

Steps:
![Screenshot (309)](https://user-images.githubusercontent.com/114911122/193539766-7a5a14af-3863-4fc8-9ffa-24af5b6ae028.png)

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by plagoa** [comment]
Hello. What version did you upgrade from?

In UI Kit v4 the Table component was replaced by a different version from v3. in order to minimize impact on the migration, we introduced the compatibility package where the old `Table` was moved to. Please check the "Compatibility package" section on the Migration Guide:
https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page|

After installing that package you should only have to change the import for the Table component.

**Comment by francisco-guilherme** [comment]
Hi @chandinigangupalli, we'll close this issue for now.
Feel free to re open it if needed.

Tks
