### ISSUE TITLE
Horizontal Navigation - Level 2: layout inconsistencies compared to Design System mocks

### ISSUE THREAD

**Issue by paulaclemente** [lumada-design/hv-uikit-react#3311]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

1. Level 2 menu option that is selected does not have a bottom border (only label is in Bold).
<img width="368" alt="Screenshot 2023-05-05 at 11 10 38" src="https://user-images.githubusercontent.com/412752/236442248-7bf48bd3-97ea-4464-b662-693cc2cfd758.png">

2. Height of the L2 bar is 64px.

### Expected behavior 🤔

1. Level 2 menu option that is selected has a bottom border.
<img width="894" alt="Screenshot 2023-05-05 at 11 09 20" src="https://user-images.githubusercontent.com/412752/236442676-10fa82ef-e652-446f-864b-d646eb1053b2.png">

2. Height of the L2 bar should be **56px**, according to DS mocks
![MicrosoftTeams-image](https://user-images.githubusercontent.com/412752/236443585-3646a9e9-7a22-4acd-9dfd-391d570b9821.png)

**Comment by MEsteves22** [comment]
Hello, this issue was fixed one the latest version. Thank you!

![Screenshot 2023-05-17 at 12 20 37](https://github.com/lumada-design/hv-uikit-react/assets/43220251/47d27d2b-7d83-45b8-a03a-dfe984974da1)

![Screenshot 2023-05-17 at 12 21 29 (2)](https://github.com/lumada-design/hv-uikit-react/assets/43220251/0b406a16-28ec-4a3e-939c-186e3ac732e7)
