### ISSUE TITLE
Can we able to move the up/down arrow icon from the left to the right side of the HvAccordion?

### ISSUE THREAD

**Issue by rajeeshusr** [lumada-design/hv-uikit-react#3730]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Here I have attached the current behaviour of Accordion

![image](https://github.com/lumada-design/hv-uikit-react/assets/5685106/bd7dfbcf-15cb-4e7c-a27d-01000c427c26)

### Expected behavior 🤔

Here I have attached the expected behaviour of Accordion

The OEE label needs to show on the left and the down/up arrow needs to show on the right of the header.

![2023-10-11_21h19_57](https://github.com/lumada-design/hv-uikit-react/assets/5685106/2e840bb2-6263-4066-96f7-cd53f3162365)

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

1.
2.
3.
4.

### Your Environment 🌎

Device: Laptop
OS: Windows 11 Enterprise
Browser: Chrome
Version: 117.0.5938

**Comment by zettca** [comment]
Hey @rajeeshusr 👋 

The `HvAccordion` currently doesn't support changing the side of the expander arrow to the right because it's not part of the Design System spec.
If you need that for your application, you can probably achieve it through overriding the styles (eg. `flexDirection: "row-reverse")`, or building your own component (probably the best option) leveraging our icons and [`HvPanel`](https://lumada-design.github.io/uikit/master/?path=/docs/components-panel--docs). You can take a look at the implementation on [HvAccordion](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/components/Accordion/Accordion.tsx#L191-L203) for inspiration

**Comment by francisco-guilherme** [comment]
Hi @rajeeshusr, going to close this for now.
Let us know if you need more support from us.
