### ISSUE TITLE
Show Input's status message not only for invalid status

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3813]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Hi!

For the `HvInput` component we have `status` and `statusMessage` props. The `status="invalid"` works well for displaying errors, but it would be nice to be able to use other types of statuses. For example, I want to display some kind of notification to the user about a change in this field or something like that.

### Examples 🌈

<img width="920" alt="Screenshot 2023-11-15 at 18 06 28" src="https://github.com/lumada-design/hv-uikit-react/assets/21086792/71cdd987-9792-4f0b-87ff-3e7bd90c57f2">

Can we extend the ability to show `statusMessage` not only for `"invalid"` status but also for other statuses with a corresponding color scheme?

```tsx
  <HvTextArea
    label="Source Expression"
    multiline
    rows={4}
    status="valid" // or info
    statusMessage="test message"
  />

```

and it renders blue or green color scheme for the input

<img width="908" alt="Screenshot 2023-11-15 at 18 07 27" src="https://github.com/lumada-design/hv-uikit-react/assets/21086792/2f097a40-4c03-4c71-9349-774652d741e2">

### Motivation 🔦

It is necessary to realize highlighting of some fields with information for the user. This feature may be useful not only in my case

**Comment by zettca** [comment]
Hey @Quernest 👋 Sorry for the delay

Currently Form Component's `status` is intended to be for form validation status, and isn't planned to be generic - therefore a `status="info"` (or generic) isn't something we plan on adding.

Regarding `status="valid"` with "different styles", it currently isn't possible because of the way `HvWarningText` renders the live region text. We're evaluating whether we can change the component to render the value without this leading to breaking changes.

For now, I would suggest that you create a custom input, without a custom Warning/InfoText, leveraging UI Kit's [FormElement API & components](https://lumada-design.github.io/uikit/master/?path=/docs/guides-forms-form-element--docs)

**Comment by Quernest** [comment]
> Hey @Quernest 👋 Sorry for the delay
> 
> Currently Form Component's `status` is intended to be for form validation status, and isn't planned to be generic - therefore a `status="info"` (or generic) isn't something we plan on adding.
> 
> Regarding `status="valid"` with "different styles", it currently isn't possible because of the way `HvWarningText` renders the live region text. We're evaluating whether we can change the component to render the value without this leading to breaking changes.
> 
> For now, I would suggest that you create a custom input with a custom Warning/InfoText, leveraging UI Kit's [FormElement API & components](https://lumada-design.github.io/uikit/master/?path=/docs/guides-forms-form-element--docs)

OK, thanks :)
