### ISSUE TITLE
HvSnackbarContent message truncated

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3918]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

The following code calls an error notification
```tsx
const { enqueueSnackbar } = useHvSnackbar()

enqueueSnackbar(error.message, { variant: 'error' })
```
but the error text is too large and is truncated accordingly.

<img width="479" alt="Screenshot 2023-12-27 at 15 45 25" src="https://github.com/lumada-design/hv-uikit-react/assets/21086792/e8ae79a5-c2c6-4d80-b7d2-92c132d6175c">

### Expected behavior 🤔

Could you implement a scroll inside the notification block or a button to copy notification text? This will help to get the full text of the message.

**Comment by zettca** [comment]
Hey @Quernest 👋 

According to Design System spec, Snackbars shouldn't have more than 3 lines of text. Here's a few options:
- reduce the amount of text being shown
- use `HvOverflowTooltip` to hide the text if it overflows - we have [some samples here](https://lumada-design.github.io/uikit/master/?path=/docs/components-snackbar--docs#variants)
- use an Banner instead of a Snackbar

Nevertheless, you can style the snackbar and/or add actions to it, leveraging the `enqueueSnackbar`'s `action` (there's an [action example here](https://lumada-design.github.io/uikit/master/?path=/docs/components-snackbar-provider--docs)):
```tsx
enqueueSnackbar("This is a snackbar.", {
  snackbarContentProps: {
    classes: {
      messageText: "myClass"
    },
    // 👆 override styles
    action: { id: "action", label: "Close" },
    actionCallback: (evt, id, action) => {
      console.log("Clicked action", action);
    },
    // 👆 override styles
  },
});
```

Let me know if this helps

**Comment by Quernest** [comment]
@zettca That will definitely solve the problem, thank you

**Comment by zettca** [comment]
Nice 👌
