### ISSUE TITLE
Locale not presented for japanese

### ISSUE THREAD

**Issue by gobarcanin** [lumada-design/hv-uikit-react#4219]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Date picker is presenting date as DD/MM/YYYY

### Expected behavior 🤔

Date picker should present date as YYYY/MM/DD

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1. Add HvDatePicker to code
2. Add locale for japan "ja-ja"

### Context 🔦

I'm trying to create date picker to represent selected date in proper format

**Comment by MEsteves22** [comment]
Hello 👋

Thanks for reporting this, we'll take a look.

**Comment by plagoa** [comment]
Hello @gobarcanin can you please provide some more information? Where were you expecting to have the date in the YYYY/MM/DD format? We made some changes that you can see below:

![image](https://github.com/user-attachments/assets/4d2f8bdf-82b8-488a-aeb8-475601af2b7f)

In the area highlighted in red the date is presented in the format specified by Design System, in green the changes that were made (not yet available) that allow the user to use a different format other than DD/MM/YYYY.

**Comment by gobarcanin** [comment]
はい、we were doing some implementation for our client and client expected for date in red to be same as locale. So if we enforce ja-JP it was not visible for date in red. Sorry for long time to reply

**Comment by gobarcanin** [comment]
Sorry, I've completely misinterpreted your reply. Red marked date is expected to be presented as green date

**Comment by gobarcanin** [comment]
Hi, any feedback on this issue?

**Comment by zettca** [comment]
Thanks for the clarification @gobarcanin, and apologies for the delay.

We'll look into this issue!
